#!/bin/bash

# Deployment script for bug fixes
# This lists the files that need to be uploaded to the server

echo "=================================================="
echo "Files to Deploy to Server"
echo "=================================================="
echo ""
echo "The following files need to be uploaded to your server:"
echo ""
echo "1. loan/classes/BatchManager.php"
echo "2. classes/send_alert.php"
echo "3. alert/coop.php"
echo "4. loan/accountNo.php"
echo "5. index.php"
echo "6. DELETE: loan/beneficiary1.php (deprecated)"
echo ""
echo "=================================================="
echo "Deployment Methods:"
echo "=================================================="
echo ""
echo "Option 1: Using cPanel File Manager"
echo "  1. Login to cPanel at https://emmaggi.com/cpanel"
echo "  2. Open File Manager"
echo "  3. Navigate to public_html/coop_admin/"
echo "  4. Upload each file to its corresponding location"
echo "  5. Delete loan/beneficiary1.php"
echo ""
echo "Option 2: Using FTP Client (FileZilla, etc)"
echo "  1. Connect to your server via FTP"
echo "  2. Navigate to /home/emmaggic/public_html/coop_admin/"
echo "  3. Upload each file"
echo "  4. Delete loan/beneficiary1.php"
echo ""
echo "Option 3: Using SSH/Git (if available)"
echo "  ssh your-username@emmaggi.com"
echo "  cd /home/emmaggic/public_html/coop_admin"
echo "  git pull origin master"
echo ""
echo "=================================================="
echo "After deployment, refresh the page to verify:"
echo "https://www.emmaggi.com/coop_admin/loan/home.php"
echo "=================================================="

